


--TASK 3 

--QUESTION 1
SELECT * FROM VIDEODB.CONTACT;
SELECT * FROM VIDEODB.RENTAL;
SELECT * FROM VIDEODB.RENTAL_ITEM;
SELECT * FROM VIDEODB.COMMON_LOOKUP;


SELECT CONTACT_ID, LAST_NAME, COALESCE(FIRST_NAME, 'JUN 2011 TTL'),
TO_CHAR(SUMA, '$9,999.99'), 
TO_CHAR(AVER, '$99.99') FROM VIDEODB.CONTACT CONT
RIGHT OUTER JOIN (

SELECT CUSTOMER_ID, SUM(RENTAL_ITEM_PRICE) SUMA, AVG(RENTAL_ITEM_PRICE) AVER  
FROM VIDEODB.COMMON_LOOKUP COMM INNER JOIN (

SELECT RENTAL_ITEM_TYPE, CUSTOMER_ID, RENTAL_ITEM_PRICE FROM  VIDEODB.RENTAL_ITEM REIT INNER JOIN (

SELECT RENTAL_ID, CUSTOMER_ID FROM VIDEODB.RENTAL 
WHERE CHECK_OUT_DATE > TO_DATE('31-MAY-11',  'DD-MON-YY') AND
CHECK_OUT_DATE < TO_DATE('01-JUL-11',  'DD-MON-YY')) RENT ON (REIT.RENTAL_ID = RENT.RENTAL_ID)) 
RENTPLIT ON (COMM.COMMON_LOOKUP_ID = RENTPLIT.RENTAL_ITEM_TYPE) 

WHERE COMMON_LOOKUP_TYPE = '1-DAY RENTAL'
AND COMMON_LOOKUP_TABLE = 'RENTAL_ITEM' 
group by ROLLUP( CUSTOMER_ID))
HUGET ON (HUGET.CUSTOMER_ID = CONT.CONTACT_ID)
ORDER BY FIRST_NAME, LAST_NAME 
;

--QUEST 2
SELECT * FROM LEAGUEDB.PLAYER;
SELECT * FROM LEAGUEDB.PLAYERSTATS;


SELECT FIRSTNAME, LASTNAME FROM LEAGUEDB.PLAYERSTATS PS
RIGHT OUTER JOIN LEAGUEDB.PLAYER P 
ON(P.PLAYERID = PS.PLAYER) 
WHERE PS.GOALS = 0 OR PS.GOALS IS NULL
ORDER BY FIRSTNAME, LASTNAME;



SELECT  FIRSTNAME, LASTNAME FROM LEAGUEDB.PLAYER WHERE PLAYERID IN 
(
SELECT  playerid FROM LEAGUEDB.PLAYERSTATS PS RIGHT OUTER JOIN LEAGUEDB.PLAYER P ON
(P.PLAYERID = PS.PLAYER) 
WHERE PS.GOALS = 0 OR PS.GOALS IS NULL
)
;





SELECT FIRSTNAME, LASTNAME FROM LEAGUEDB.PLAYER PL INNER JOIN
LEAGUEDB.PLAYERSTATS PS ON 
(PL.PLAYERID = PS.PLAYER) WHERE GOALS = 0
UNION
SELECT FIRSTNAME, LASTNAME FROM LEAGUEDB.PLAYER PL LEFT OUTER JOIN
LEAGUEDB.PLAYERSTATS PS ON 
(PL.PLAYERID = PS.PLAYER) WHERE GOALS IS NULL;



SELECT FIRSTNAME, LASTNAME FROM LEAGUEDB.PLAYER PL LEFT OUTER JOIN
LEAGUEDB.PLAYERSTATS PS ON 
(PL.PLAYERID = PS.PLAYER)
MINUS
SELECT  FIRSTNAME, LASTNAME FROM LEAGUEDB.PLAYER PL LEFT OUTER JOIN
LEAGUEDB.PLAYERSTATS PS ON 
(PL.PLAYERID = PS.PLAYER) WHERE GOALS > 0 ;

--Q3
SELECT * FROM VIDEODB.ITEM;
SELECT * FROM VIDEODB.RENTAL;
SELECT * FROM VIDEODB.RENTAL_ITEM;
SELECT * FROM VIDEODB.COMMON_LOOKUP;


SELECT * FROM VIDEODB.ITEM WHERE ITEM_TITLE LIKE '%Star Wars%';




SELECT * FROM VIDEODB.RENTAL where 
CHECK_OUT_DATE > TO_DATE('30-SEP-11','DD-MON-YY') AND
CHECK_OUT_DATE < TO_DATE('1-NOV-11','DD-MON-YY');






SELECT ITEM_ID, ITEM_TITLE, COUNT(ITEM_TITLE) TIMESRENT, 
TO_CHAR(SUM(RENTAL_ITEM_PRICE),'$999.99') TTL FROM VIDEODB.RENTAL RENT INNER JOIN (

SELECT RENTAL_ID, REIT.ITEM_ID, RENTAL_ITEM_PRICE, ITEM_TITLE FROM VIDEODB.RENTAL_ITEM REIT INNER JOIN (

SELECT ITEM_ID , ITEM_TITLE FROM VIDEODB.ITEM ITEM INNER JOIN (

SELECT  COMMON_LOOKUP_ID

FROM VIDEODB.COMMON_LOOKUP WHERE COMMON_LOOKUP_TYPE = 'DVD_WIDE_SCREEN')

LOOK ON(ITEM.ITEM_TYPE = LOOK.COMMON_LOOKUP_ID) WHERE ITEM_TITLE LIKE '%Star Wars%') 
LOOKITEM ON (REIT.ITEM_ID = LOOKITEM.ITEM_ID)) HUGET ON(HUGET.RENTAL_ID = RENT.RENTAL_ID) 
where 
CHECK_OUT_DATE > TO_DATE('30-SEP-11','DD-MON-YY') AND
CHECK_OUT_DATE < TO_DATE('1-NOV-11','DD-MON-YY')

GROUP BY ITEM_ID, ITEM_TITLE
ORDER BY ITEM_TITLE
;
--Q4
SELECT * FROM LEAGUEDB.TEAM;

SELECT TEAMNAME, COALESCE(SPONSOR,'UNKNOWN') SPONSOR, MANAGER, HEADCOACH FROM LEAGUEDB.TEAM
ORDER BY TEAMNAME ASC;



